<?php
namespace App\Classes\TimeKeeping;

class Scheduling {
    public function query($first, $last) {
        $script = "employees.id, employees.firstname, employees.middlename, employees.lastname,employees.suffix,employees.profile_img, 
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 1 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'sun',
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 2 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'mon',
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 3 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'tue',
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 4 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'wed',
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 5 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'thu',
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 6 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'fri',
        MAX(CASE WHEN schedulings.date >= '".$first."' AND schedulings.date <= '".$last."' THEN (CASE WHEN DAYOFWEEK(schedulings.date) = 7 THEN CONCAT((CASE WHEN schedulings.start_time IS NOT NULL THEN DATE_FORMAT(schedulings.start_time, '%H:%i') ELSE '' END), ' - ', (CASE WHEN schedulings.end_time IS NOT NULL THEN DATE_FORMAT(schedulings.end_time, '%H:%i') ELSE '' END),'|', (CASE WHEN schedulings.work_assignment_id IS NOT NULL THEN work_assignments.title ELSE '' END),'|',schedulings.type,'|',(CASE WHEN schedulings.earning_id IS NOT NULL THEN earnings.name ELSE schedulings.type_description END)) END) END) 'sat'";

        return $script;
    }

    
}
?>